### ISSUE TITLE
Make this project better accessable for external contributors

### ISSUE THREAD

**Issue by livio-a** [zitadel/oidc#116]
- [x] enable workflow on PR from forks #117 
- [x] sem rel #117 
- [ ] publish some roadmap / ideas
- [x] create issue templates #117 
- [x] discussions?
- [ ] PR template
- [ ] documentation
  - [ ] explain when and how to use what (package structure, also of examples)
  - [ ] diagram? (https://github.com/caos/oidc/issues/144#issue-1071600880)
- [x] update server example (see also #155)

**Comment by arianvp** [comment]
Hey!

One thing that would really help me as a contributor would be a more complete test suite.  I suppose you are running against the oidc conformance test suite, but I was wondering if there is also a plan to add a larger set of unit tests to make iterative development easier?  Going through the oidc conformance tests is a rather tedious manual process.

**Comment by fforootd** [comment]
Hi @arianvp 

We are definitly commited to improve the test coverage of this project over time.
Many of my collegaues are in there holidays these days, but we will check what we can do early next year to improve the situation 😁

**Comment by arianvp** [comment]
I hope everybody is enjoying their holidays! Talk to you in the new year then! 🎆🎇🧨

**Comment by fforootd** [comment]
Looking forward to engage with you next year and have a safe start into 2022 🎆
